### ISSUE TITLE
CartPole: naming inconsistencies

### ISSUE THREAD

**Issue by GMMDMDIDEMS** [pyrddlgym-project/rddlrepository#26]
To remain consistent, the name within the `__init__` files should match the name of the parent folder.

So for [CartPole Continuous](https://github.com/pyrddlgym-project/rddlrepository/blob/main/rddlrepository/archive/gym/CartPole/Continuous/__init__.py), we should change `'name': 'Cartpole_Continuous',` to `'name': 'CartPole_Continuous',`.

And the same for the discrete version of CartPole.

**Comment by mike-gimelfarb** [comment]
Thanks, this has been fixed.
